### ISSUE TITLE
hobbit:KPI subclasses should define ordering for their instances

### ISSUE THREAD

**Issue by denkv** [hobbit-project/ontology#3]
We need to be able to correctly sort KPI values to implement [leaderboards](https://github.com/hobbit-project/platform/issues/83).

At least ascending and descending sorting orders are needed.

Default ordering may be specified in `hobbit:KPI` class.

**Comment by denkv** [comment]
We need some names for that since we haven't found suitable existing ontology for that yet.

What about `hobbit:ordering`, `hobbit:ascendingOrder`, `hobbit:descendingOrder`? Maybe something along the lines of _grading_ or _ranking_?

**Comment by MichaelRoeder** [comment]
`hobbit:ranking` is fine.
But the resources `AscendingOrder` and `DescendingOrder` should be written with uppercase letters at the beginning.
