### ISSUE TITLE
Regularly executable challenges

### ISSUE THREAD

**Issue by denkv** [hobbit-project/ontology#7]
- new property for period of challenge execution, maybe `hobbit:executionPeriod`
- final date of challenge execution, maybe `hobbit:executionEndDate` (currently `executionDate` exists for start date)

**Comment by MichaelRoeder** [comment]
* `executionDate` is the date of execution for a "normal" challenge OR the date at which it is executed the first time for a "repeatable" challenge
* `registrationCutoffDate` is the date of the last execution
* `executionPeriod` is the amount of time before the next execution takes place
* `dateOfNextExecution` is the date at which the execution should take place next time
